### ISSUE TITLE
Gantt Chart

### ISSUE THREAD

**Issue by thkearney** [kwboe/Crypto-Capstone#3]
https://cgacademy-my.sharepoint.com/:x:/g/personal/torin_h_kearney_uscga_edu/Eb0cWL3uXv5CnI9ngRWzisgB8Dy5nB9xiUppyAPDowatCQ?email=Ryan.T.Quarry%40uscg.mil&e=QfSch1

**Comment by rquarry** [comment]
@thkearney Interested in seeing this artifact. Can you put the OneDrive or O365 link in the description?

**Comment by thkearney** [comment]
Added sir! Apologies for the delay @rquarry
